title: Technohumanizm &mdash; o ludziach, technologii i życiu w zgodzie ze sobą
email: kontakt@technohumanizm.pl
description: Technohumanizm &mdash; o ludziach, technologii i życiu w zgodzie ze sobą
baseurl: ""
url: "https://technohumanizm.pl"
date_format: "%d/%m/%Y"
instagram_username: technohumanizm
facebook_username: technohumanizm
disqus_shortname: martasztybor
google_analytics: UA-152704621-1

# Build settings
markdown: kramdown
paginate: 6
sass:
  compressed: true
plugins_dir: 
  - jekyll-paginate
gems: [jekyll-paginate]